/**
 * @file tests/core/mapper.test.js
 * @description Integration tests for the main mapper logic.
 * These tests use fixture files to verify the end-to-end variable extraction process,
 * from directory scanning to result formatting.
 */

import { test, describe, it, assert } from 'node:test';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { mapEnvironmentVariables } from '../../src/core/mapper.js';
import { OUTPUT_FORMATS } from '../../src/utils/constants.js';

// Helper to get the absolute path to the fixtures directory
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const fixturesPath = path.resolve(__dirname, '../fixtures/sample-project');

describe('core/mapper', () => {
  describe('mapEnvironmentVariables()', () => {
    it('should correctly find all environment variables in the sample project', async () => {
      const result = await mapEnvironmentVariables({
        directory: fixturesPath,
        format: OUTPUT_FORMATS.JSON,
      });

      const data = JSON.parse(result.content);
      const varNames = Object.keys(data).sort();

      const expectedVars = [
        'API_KEY',
        'API_SECRET',
        'DB_HOST',
        'DB_NAME',
        'DB_PASSWORD',
        'DB_PORT',
        'DB_SSL_MODE',
        'DB_USER',
        'ENABLE_HTTPS',
        'NODE_ENV',
        'PORT',
        'VAR_WITH_UNDERSCORES_AND_NUMBERS_123',
      ].sort();

      assert.deepStrictEqual(varNames, expectedVars, 'Should find all unique environment variables');
    });

    it('should return a detailed report with correct file paths and line numbers', async () => {
      const result = await mapEnvironmentVariables({
        directory: fixturesPath,
        format: OUTPUT_FORMATS.JSON,
      });

      const data = JSON.parse(result.content);

      // Check a variable from the root file (api.js)
      assert.strictEqual(data.API_KEY.length, 1, 'API_KEY should have one occurrence');
      assert.strictEqual(data.API_KEY[0].file, 'tests/fixtures/sample-project/api.js', 'File path for API_KEY should be correct');
      assert.strictEqual(data.API_KEY[0].line, 9, 'Line number for API_KEY should be correct');

      // Check a variable from the nested file (utils/db.js)
      assert.strictEqual(data.DB_USER.length, 1, 'DB_USER should have one occurrence');
      assert.strictEqual(data.DB_USER[0].file, 'tests/fixtures/sample-project/utils/db.js', 'File path for DB_USER should be correct');
      assert.strictEqual(data.DB_USER[0].line, 12, 'Line number for DB_USER should be correct');

      // Check a variable with multiple occurrences
      assert.strictEqual(data.PORT.length, 2, 'PORT should have two occurrences');
      const portOccurrences = data.PORT.sort((a, b) => a.line - b.line);
      assert.strictEqual(portOccurrences[0].file, 'tests/fixtures/sample-project/api.js');
      assert.strictEqual(portOccurrences[0].line, 13, 'First PORT occurrence line number should be correct');
      assert.strictEqual(portOccurrences[1].file, 'tests/fixtures/sample-project/api.js');
      assert.strictEqual(portOccurrences[1].line, 29, 'Second PORT occurrence line number should be correct');
    });

    it('should generate a simple list of unique, sorted variable names', async () => {
      const result = await mapEnvironmentVariables({
        directory: fixturesPath,
        format: OUTPUT_FORMATS.LIST,
      });

      const expectedList = [
        'API_KEY',
        'API_SECRET',
        'DB_HOST',
        'DB_NAME',
        'DB_PASSWORD',
        'DB_PORT',
        'DB_SSL_MODE',
        'DB_USER',
        'ENABLE_HTTPS',
        'NODE_ENV',
        'PORT',
        'VAR_WITH_UNDERSCORES_AND_NUMBERS_123',
      ].join('\n');

      assert.strictEqual(result.content, expectedList, 'Output should be a sorted, newline-separated list');
      assert.strictEqual(result.isFile, false, 'List format should not be marked as a file');
    });

    it('should generate content for a .env.example file', async () => {
      const result = await mapEnvironmentVariables({
        directory: fixturesPath,
        format: OUTPUT_FORMATS.ENV,
      });

      assert.ok(result.content.includes('# This file was auto-generated by env-var-mapper'), 'Should contain the header');
      assert.ok(result.content.includes('API_KEY='), 'Should contain API_KEY');
      assert.ok(result.content.includes('DB_HOST='), 'Should contain DB_HOST');
      assert.ok(result.content.endsWith('VAR_WITH_UNDERSCORES_AND_NUMBERS_123=\n'), 'Should list all variables ending with = and a newline');
      assert.strictEqual(result.isFile, true, 'env format should be marked as a file');
      assert.strictEqual(result.fileName, '.env.example', 'env format should have the default filename');
    });

    it('should handle ignore patterns correctly', async () => {
      // Ignore the `utils` directory
      const result = await mapEnvironmentVariables({
        directory: fixturesPath,
        format: OUTPUT_FORMATS.JSON,
        ignorePatterns: ['**/utils/**'],
      });

      const data = JSON.parse(result.content);
      const varNames = Object.keys(data).sort();

      // Variables from `db.js` should be missing
      assert.strictEqual(data.DB_HOST, undefined, 'DB_HOST from ignored file should not be present');
      assert.strictEqual(data.DB_USER, undefined, 'DB_USER from ignored file should not be present');

      // Variables from `api.js` should still be present
      assert.ok(data.API_KEY, 'API_KEY should be present');
      assert.ok(data.PORT, 'PORT should be present');
    });

    it('should return an empty result for a directory with no matching files', async () => {
      // Use the current directory but with a glob that won't match anything
      const emptyFixturesPath = path.resolve(__dirname, '../fixtures');
      const result = await mapEnvironmentVariables({
        directory: emptyFixturesPath,
        format: OUTPUT_FORMATS.LIST,
      });

      assert.strictEqual(result.content, 'No environment variables found.', 'Should report that no variables were found');
    });

    it('should throw an error for an invalid directory', async () => {
      const invalidDir = path.join(fixturesPath, 'non-existent-dir');
      await assert.rejects(
        mapEnvironmentVariables({
          directory: invalidDir,
          format: OUTPUT_FORMATS.LIST,
        }),
        {
          message: `Failed to map environment variables: Failed to scan directory "${invalidDir}": ENOENT: no such file or directory, scandir '${invalidDir}'`,
        },
        'Should throw an error for a non-existent directory'
      );
    });

    it('should throw an error for an unsupported format', async () => {
      await assert.rejects(
        mapEnvironmentVariables({
          directory: fixturesPath,
          format: 'unsupported-format',
        }),
        {
          message: 'Failed to map environment variables: Unsupported output format: "unsupported-format". Supported formats are: list, detail, json, env.',
        },
        'Should throw an error for an invalid format'
      );
    });

    it('should correctly handle files with syntax errors by skipping them', async () => {
      const pathWithBrokenFile = path.resolve(__dirname, '../fixtures');
      // This will scan `sample-project` (good) and `broken-project` (bad)
      const result = await mapEnvironmentVariables({
        directory: pathWithBrokenFile,
        format: OUTPUT_FORMATS.JSON,
      });
      const data = JSON.parse(result.content);
      const varNames = Object.keys(data);

      // It should still find all the variables from the valid project
      assert.ok(varNames.length > 10, 'Should find variables from the valid project');
      assert.ok(data.API_KEY, 'API_KEY from valid project should be present');

      // The test implicitly passes if it doesn't crash on the broken file,
      // as `mapEnvironmentVariables` is designed to be resilient.
    });
  });
});