/**
 * This file was generated by jsdoc-to-zod.
 * Do not make changes to this file directly.
 */

import { z } from 'zod';

// Generated from UserID
export const userIDSchema = z.string().describe('A unique identifier for a user.');

// Generated from UserProfile
export const userProfileSchema = z.object({
  id: z.custom<UserID>().describe('The unique identifier for the user.'),
  name: z.string().describe('The full name of the user.'),
  email: z.string().optional().describe('The user\'s email address. It\'s optional.'),
  age: z.number().describe('The user\'s age in years.'),
  isActive: z.boolean().describe('Whether the user\'s account is active.'),
  tags: z.array(z.string()).describe('An array of tags associated with the user.'),
  metadata: z.object({}).describe('An object for storing arbitrary data.'),
  'metadata.theme': z.string().describe('The user\'s preferred theme.'),
  'metadata.lastLogin': z.date().describe('The timestamp of the last login.')
});

// Generated from createItem
export const createItemSchema = z.object({
  name: z.string().describe('The name of the item to create.'),
  quantity: z.number().describe('The starting quantity.'),
  isAvailable: z.boolean().optional().describe('Whether the item is available for purchase.'),
  categories: z.array(z.string()).describe('An array of category names.'),
  owner: z.custom<UserProfile>().describe('The profile of the user who owns this item.')
});

// Generated from getUserData
export const getUserDataSchema = z.object({
  userId: z.string().describe('The ID of the user to fetch.')
});

// Generated from processUnionType
export const processUnionTypeSchema = z.object({
  input: z.union([z.string(), z.number()]).describe('An input that can be either a string or a number.')
});

// Generated from MaybeID
export const maybeIDSchema = z.union([z.string(), z.number(), z.null()]);