/**
 * @file test/crontab-builder.test.js
 * @description Unit tests for ensuring the generated crontab output is syntactically correct.
 * This file tests the `buildCrontab` function to verify its output with various inputs,
 * including different schedules, environment variables, headers, and edge cases.
 */

import { test, describe, it, mock } from 'node:test';
import assert from 'node:assert';
import { buildCrontab } from '../src/generators/crontab-builder.js';

/**
 * @typedef {import('../src/parsers/comment-extractor.js').CronSchedule} CronSchedule
 */

describe('buildCrontab', () => {
  // Mock Date.now() to ensure generated headers are consistent for snapshots.
  const MOCK_DATE = new Date('2023-10-27T10:00:00.000Z');
  mock.method(global, 'Date', function (...args) {
    if (args.length === 0) {
      return MOCK_DATE;
    }
    return new Date(...args);
  });

  const DEFAULT_HEADER = [
    '# ============================================================================',
    '# DO NOT EDIT THIS FILE DIRECTLY!',
    '# This file is automatically generated by the "declarative-cron-parser" tool.',
    '# Changes will be overwritten on the next run.',
    '# To add or modify cron jobs, edit the @cron comments in your source files.',
    `# Generated on: ${MOCK_DATE.toISOString()}`,
    '# ============================================================================',
  ].join('\n');

  it('should generate a crontab with a single valid schedule', () => {
    /** @type {CronSchedule[]} */
    const schedules = [
      {
        schedule: '0 5 * * *',
        command: '/usr/bin/node /app/task.js',
        sourceFile: '/app/task.js',
        sourceLine: 10,
      },
    ];

    const expected = [
      DEFAULT_HEADER,
      '# Source: /app/task.js:10',
      '0 5 * * * /usr/bin/node /app/task.js',
    ].join('\n\n') + '\n';

    const result = buildCrontab({ schedules });
    assert.strictEqual(result, expected);
  });

  it('should generate a crontab with multiple schedules', () => {
    /** @type {CronSchedule[]} */
    const schedules = [
      {
        schedule: '0 5 * * *',
        command: '/usr/bin/node /app/task1.js',
        sourceFile: '/app/task1.js',
        sourceLine: 5,
      },
      {
        schedule: '*/15 * * * 1-5',
        command: '/usr/bin/python3 /app/reporter.py',
        sourceFile: '/app/reporter.py',
        sourceLine: 8,
      },
    ];

    const expected = [
      DEFAULT_HEADER,
      '# Source: /app/task1.js:5\n0 5 * * * /usr/bin/node /app/task1.js',
      '# Source: /app/reporter.py:8\n*/15 * * * 1-5 /usr/bin/python3 /app/reporter.py',
    ].join('\n\n') + '\n';

    const result = buildCrontab({ schedules });
    assert.strictEqual(result, expected);
  });

  it('should generate a crontab with only the header for an empty schedule list', () => {
    const expected = DEFAULT_HEADER + '\n';
    const result = buildCrontab({ schedules: [] });
    assert.strictEqual(result, expected);
  });

  it('should generate a crontab with only the header when options are null or undefined', () => {
    const expected = DEFAULT_HEADER + '\n';
    assert.strictEqual(buildCrontab(null), expected);
    assert.strictEqual(buildCrontab(undefined), expected);
    assert.strictEqual(buildCrontab({}), expected);
  });

  it('should include environment variables at the top of the crontab', () => {
    const env = {
      SHELL: '/bin/bash',
      PATH: '/usr/local/bin:/usr/bin:/bin',
      CUSTOM_VAR: 'some_value',
    };
    const expected = [
      DEFAULT_HEADER,
      'SHELL="/bin/bash"',
      'PATH="/usr/local/bin:/usr/bin:/bin"',
      'CUSTOM_VAR="some_value"',
    ].join('\n\n') + '\n';

    const result = buildCrontab({ env });
    assert.strictEqual(result, expected);
  });

  it('should correctly handle and escape quotes in environment variable values', () => {
    const env = {
      COMPLEX_VAR: 'a "quoted" string',
    };
    const expected = [
      DEFAULT_HEADER,
      'COMPLEX_VAR="a \\"quoted\\" string"',
    ].join('\n\n') + '\n';

    const result = buildCrontab({ env });
    assert.strictEqual(result, expected);
  });

  it('should include a custom header before the default header', () => {
    const customHeader = '# My Custom Project Header\n# Version: 1.2.3';
    const expected = [
      customHeader,
      DEFAULT_HEADER,
    ].join('\n\n') + '\n';

    const result = buildCrontab({ header: customHeader });
    assert.strictEqual(result, expected);
  });

  it('should trim whitespace from custom headers', () => {
    const customHeader = '  \n # Padded Header \n  ';
    const expected = [
      '# Padded Header',
      DEFAULT_HEADER,
    ].join('\n\n') + '\n';

    const result = buildCrontab({ header: customHeader });
    assert.strictEqual(result, expected);
  });

  it('should generate a full crontab with header, env vars, and multiple schedules', () => {
    const options = {
      header: '# My App Cron Jobs',
      env: {
        NODE_ENV: 'production',
        API_KEY: 'secret123',
      },
      schedules: [
        {
          schedule: '0 0 * * *',
          command: 'backup.sh',
          sourceFile: '/scripts/backup.sh',
          sourceLine: 1,
        },
        {
          schedule: '0 12 * * *',
          command: 'report.js',
          sourceFile: '/scripts/report.js',
          sourceLine: 4,
        },
      ],
    };

    const expected = [
      '# My App Cron Jobs',
      DEFAULT_HEADER,
      'NODE_ENV="production"\nAPI_KEY="secret123"',
      '# Source: /scripts/backup.sh:1\n0 0 * * * backup.sh',
      '# Source: /scripts/report.js:4\n0 12 * * * report.js',
    ].join('\n\n') + '\n';

    const result = buildCrontab(options);
    assert.strictEqual(result, expected);
  });

  it('should throw CrontabBuilderError for invalid schedules array', () => {
    assert.throws(
      () => buildCrontab({ schedules: 'not-an-array' }),
      {
        name: 'CrontabBuilderError',
        message: 'Schedules must be provided as an array.',
      }
    );
  });

  it('should throw CrontabBuilderError for invalid schedule object in the array', () => {
    const invalidSchedules = [
      { schedule: '0 0 * * *', command: 'valid', sourceFile: '/valid', sourceLine: 1 },
      { schedule: '0 1 * * *', command: null, sourceFile: '/invalid', sourceLine: 2 }, // Missing command
    ];
    assert.throws(
      () => buildCrontab({ schedules: invalidSchedules }),
      {
        name: 'CrontabBuilderError',
        message: "Invalid schedule object at index 1. It must contain 'schedule', 'command', and 'sourceFile' properties.",
      }
    );
  });

  it('should throw CrontabBuilderError for invalid environment variables object', () => {
    assert.throws(
      () => buildCrontab({ env: ['invalid', 'array'] }),
      {
        name: 'CrontabBuilderError',
        message: 'Environment variables must be provided as an object.',
      }
    );
  });

  it('should throw CrontabBuilderError for invalid environment variable name', () => {
    const invalidEnv = { '1INVALID': 'value' };
    assert.throws(
      () => buildCrontab({ env: invalidEnv }),
      {
        name: 'CrontabBuilderError',
        message: 'Invalid environment variable name: "1INVALID". Names must start with a letter or underscore, followed by letters, numbers, or underscores.',
      }
    );
  });

  it('should throw CrontabBuilderError for invalid environment variable value', () => {
    const invalidEnv = { 'VALID_KEY': { a: 1 } }; // Value is an object
    assert.throws(
      () => buildCrontab({ env: invalidEnv }),
      {
        name: 'CrontabBuilderError',
        message: 'Value for environment variable "VALID_KEY" must be a string or number.',
      }
    );
  });

  it('should handle numeric values for environment variables', () => {
    const env = {
      RETRIES: 5,
      TIMEOUT_MS: 30000,
    };
    const expected = [
      DEFAULT_HEADER,
      'RETRIES="5"\nTIMEOUT_MS="30000"',
    ].join('\n\n') + '\n';

    const result = buildCrontab({ env });
    assert.strictEqual(result, expected);
  });
});