/**
 * @file src/reporter/formatter.js
 * @description Contains functions to format collected environment variable data for various outputs.
 * This module provides formatters for a simple list, a detailed report, JSON,
 * and a `.env.example` file, using `chalk` for colorized terminal output.
 */

import chalk from 'chalk';
import path from 'node:path';
import { DEFAULT_ENV_EXAMPLE_FILENAME } from '../utils/constants.js';

/**
 * Generates a unique, sorted list of environment variable names.
 *
 * @param {Map<string, object[]>} groupedResults - A map where keys are env var names
 *   and values are arrays of their occurrences.
 * @returns {string} A newline-separated string of unique variable names.
 */
const formatAsList = (groupedResults) => {
  if (groupedResults.size === 0) {
    return chalk.yellow('No environment variables found.');
  }

  const uniqueVars = Array.from(groupedResults.keys()).sort();
  return uniqueVars.join('\n');
};

/**
 * Generates a detailed report showing each variable and its usage locations.
 *
 * @param {Map<string, object[]>} groupedResults - A map where keys are env var names
 *   and values are arrays of their occurrences.
 * @returns {string} A colorized, detailed report string.
 */
const formatAsDetail = (groupedResults) => {
  if (groupedResults.size === 0) {
    return chalk.yellow('No environment variables found.');
  }

  const uniqueVars = Array.from(groupedResults.keys()).sort();
  const reportLines = [];

  uniqueVars.forEach((varName) => {
    reportLines.push(chalk.bold.cyan(varName));
    const occurrences = groupedResults.get(varName);

    occurrences.forEach(({ file, line, column }) => {
      const relativePath = path.relative(process.cwd(), file);
      reportLines.push(`  ${chalk.gray('at')} ${relativePath}:${chalk.yellow(line)}:${chalk.yellow(column)}`);
    });
  });

  return reportLines.join('\n');
};

/**
 * Generates a JSON representation of the findings.
 *
 * @param {Map<string, object[]>} groupedResults - A map where keys are env var names
 *   and values are arrays of their occurrences.
 * @returns {string} A prettified JSON string.
 */
const formatAsJson = (groupedResults) => {
  const jsonOutput = {};
  const uniqueVars = Array.from(groupedResults.keys()).sort();

  uniqueVars.forEach((varName) => {
    jsonOutput[varName] = groupedResults.get(varName).map(({ file, line, column }) => ({
      file: path.relative(process.cwd(), file),
      line,
      column,
    }));
  });

  // The `null, 2` arguments ensure the JSON is pretty-printed.
  return JSON.stringify(jsonOutput, null, 2);
};

/**
 * Generates the content for a `.env.example` file.
 *
 * @param {Map<string, object[]>} groupedResults - A map where keys are env var names
 *   and values are arrays of their occurrences.
 * @returns {string} A string formatted for a `.env.example` file.
 */
const formatAsEnv = (groupedResults) => {
  const header = `# This file was auto-generated by env-var-mapper on ${new Date().toISOString()}
# It contains a list of all environment variables found in the project.
# Add desired default values for development.
`;

  if (groupedResults.size === 0) {
    return `${header}\n# No environment variables found.\n`;
  }

  const uniqueVars = Array.from(groupedResults.keys()).sort();
  const envLines = uniqueVars.map(varName => `${varName}=`);

  return `${header}\n${envLines.join('\n')}\n`;
};

/**
 * A map of format names to their corresponding formatter functions.
 * This allows for dynamic dispatch based on the user's chosen format.
 *
 * @type {Readonly<Map<string, Function>>}
 */
const formatters = Object.freeze(new Map([
  ['list', formatAsList],
  ['detail', formatAsDetail],
  ['json', formatAsJson],
  ['env', formatAsEnv],
]));

/**
 * Formats the collected environment variable data based on the specified format.
 *
 * @param {Map<string, object[]>} groupedResults - A map where keys are env var names
 *   and values are arrays of their occurrences.
 * @param {string} format - The desired output format (e.g., 'list', 'json').
 * @returns {{content: string, isFile: boolean, fileName: string | null}} An object containing
 *   the formatted content, a flag indicating if it's meant for a file, and the filename.
 * @throws {Error} If an unsupported format is requested.
 */
export const formatResults = (groupedResults, format) => {
  if (!formatters.has(format)) {
    throw new Error(`Unsupported output format: "${format}". Supported formats are: ${Array.from(formatters.keys()).join(', ')}.`);
  }

  const formatterFn = formatters.get(format);
  const content = formatterFn(groupedResults);

  const isFile = format === 'env';
  const fileName = isFile ? DEFAULT_ENV_EXAMPLE_FILENAME : null;

  return { content, isFile, fileName };
};