/**
 * @file src/constants.js
 * @description Defines constant values used throughout the application, such as JSDoc to Zod type mappings.
 * This centralized file helps in maintaining consistency and makes it easier to update shared values.
 */

/**
 * A mapping from lowercase JSDoc primitive type names to their corresponding Zod schema strings.
 * This is used by the Zod builder to translate types.
 *
 * The keys are lowercased to ensure case-insensitive matching.
 * The values are the Zod method calls (e.g., 'z.string()').
 *
 * @type {Object<string, string>}
 */
export const JSDOC_TO_ZOD_TYPE_MAP = Object.freeze({
  string: 'z.string()',
  number: 'z.number()',
  boolean: 'z.boolean()',
  object: 'z.object({})', // A generic, empty object. Use @typedef for specific shapes.
  array: 'z.array(z.any())', // A generic array. Use `Type[]` for specific element types.
  any: 'z.any()',
  '*': 'z.any()',
  unknown: 'z.unknown()',
  null: 'z.null()',
  undefined: 'z.undefined()',
  void: 'z.void()',
  date: 'z.date()',
  bigint: 'z.bigint()',
  symbol: 'z.symbol()',
  never: 'z.never()',
});

/**
 * A set of JSDoc tags that the parser actively looks for and processes.
 * This can be used to quickly check if a line contains a relevant tag.
 *
 * @type {Set<string>}
 */
export const SUPPORTED_JSDOC_TAGS = Object.freeze(new Set([
  '@param',
  '@arg',
  '@argument',
  '@returns',
  '@return',
  '@typedef',
  '@property',
  '@prop',
]));

/**
 * The default header prepended to every generated Zod schema file.
 * It provides context that the file is auto-generated and should not be manually edited.
 *
 * @type {string}
 */
export const ZOD_SCHEMA_FILE_HEADER = `/**
 * This file was generated by jsdoc-to-zod.
 * Do not make changes to this file directly.
 */

import { z } from 'zod';
`;