import { test, describe, it, before, after, mock } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { generate } from '../src/api.js';

/**
 * @fileoverview Unit and integration tests for the Zod generation logic.
 * This test suite verifies the core `generate` function by processing fixture files
 * and comparing the output against expected "snapshot" strings. It ensures that
 * various JSDoc patterns are correctly transformed into Zod schemas.
 *
 * @author Your Name <you@example.com>
 * @license MIT
 * @project JSDoc to Zod Schema Generator
 */

// Helper to get the directory name in ES modules
const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * Reads the content of a fixture file.
 * @param {string} fixtureName - The name of the file in the `fixtures` directory.
 * @returns {Promise<string>} The content of the file.
 */
const readFixture = (fixtureName) => {
	const fixturePath = path.join(__dirname, 'fixtures', fixtureName);
	return fs.readFile(fixturePath, 'utf8');
};

/**
 * Cleans up a string for consistent snapshot comparison by removing
 * extra whitespace and standardizing line endings.
 * @param {string} str - The string to normalize.
 * @returns {string} The normalized string.
 */
const normalizeWhitespace = (str) => {
	if (typeof str !== 'string') return '';
	return str.replace(/\s+/g, ' ').trim();
};

describe('Zod Schema Generator', () => {
	let consoleWarnMock;

	before(() => {
		// Mock `console.warn` to suppress expected warnings during tests
		// and to verify that warnings are issued when expected.
		consoleWarnMock = mock.method(console, 'warn', () => {});
	});

	after(() => {
		// Restore the original `console.warn` after all tests are done.
		consoleWarnMock.mock.restore();
	});

	it('should throw a TypeError if sourceCode is not a string', async () => {
		await assert.rejects(
			// @ts-ignore - Deliberately passing invalid type for testing
			generate(null),
			{
				name: 'TypeError',
				message: 'sourceCode must be a non-empty string.',
			},
			'generate() should reject when sourceCode is null'
		);

		await assert.rejects(
			// @ts-ignore - Deliberately passing invalid type for testing
			generate(123),
			{
				name: 'TypeError',
				message: 'sourceCode must be a non-empty string.',
			},
			'generate() should reject when sourceCode is a number'
		);
	});

	it('should return an empty result for source code with no relevant JSDoc', async () => {
		const sourceCode = `
      const x = 1;
      function add(a, b) { return a + b; }
      // This is a regular comment, not JSDoc.
    `;
		const result = await generate(sourceCode);
		assert.strictEqual(result.zodSchema, '', 'zodSchema should be an empty string');
		assert.strictEqual(result.schemas.length, 0, 'schemas array should be empty');
	});

	describe('Fixture: simple-object.js', () => {
		it('should generate correct Zod schemas for basic types and functions', async () => {
			const sourceCode = await readFixture('simple-object.js');
			const { zodSchema } = await generate(sourceCode, { filePath: 'simple-object.js' });

			const expectedSchema = `
        /**
         * This file was auto-generated by jsdoc-to-zod.
         * Do not make direct changes to this file.
         */

        import { z } from 'zod';

        export const User = z.object({
          id: z.string(),
          name: z.string(),
          age: z.number(),
          isActive: z.boolean().optional().default(true),
          email: z.union([
            z.string(),
            z.null(),
          ]),
        });

        export const createUserParams = z.object({
          user: User,
        });

        export const createUserReturn = User;

        export const defaultConfig = z.object({
          port: z.number(),
          host: z.string(),
          enableHttps: z.boolean(),
        });

        export const logMessageParams = z.object({
          message: z.string(),
          level: z.number().optional().default(1),
        });
      `;

			assert.strictEqual(
				normalizeWhitespace(zodSchema),
				normalizeWhitespace(expectedSchema),
				'Generated schema for simple-object.js does not match expected output'
			);
		});
	});

	describe('Fixture: nested-object.js', () => {
		it('should generate correct Zod schemas for nested objects and arrays', async () => {
			const sourceCode = await readFixture('nested-object.js');
			const { zodSchema } = await generate(sourceCode, { filePath: 'nested-object.js' });

			const expectedSchema = `
        /**
         * This file was auto-generated by jsdoc-to-zod.
         * Do not make direct changes to this file.
         */

        import { z } from 'zod';

        export const Tag = z.object({
          id: z.number(),
          name: z.string(),
        });

        export const Post = z.object({
          id: z.string(),
          title: z.string(),
          content: z.string(),
          tags: z.array(Tag),
          metadata: z.object({
            authorId: z.string(),
            views: z.number(),
            isPublished: z.boolean(),
          }).optional(),
        });

        export const getPostsByUserParams = z.object({
          userId: z.string(),
        });

        export const getPostsByUserReturn = z.array(Post);
      `;

			assert.strictEqual(
				normalizeWhitespace(zodSchema),
				normalizeWhitespace(expectedSchema),
				'Generated schema for nested-object.js does not match expected output'
			);
		});
	});

	describe('Fixture: custom-types.js', () => {
		it('should correctly resolve local and imported @typedef references', async () => {
			const sourceCode = await readFixture('custom-types.js');
			const { zodSchema } = await generate(sourceCode, { filePath: 'custom-types.js' });

			const expectedSchema = `
        /**
         * This file was auto-generated by jsdoc-to-zod.
         * Do not make direct changes to this file.
         */

        import { z } from 'zod';

        export const UserID = z.string();

        export const Status = z.union([
          z.string(),
          z.number(),
        ]);

        export const UserProfile = z.object({
          id: UserID,
          username: z.string(),
          status: Status,
        });

        export const Product = z.object({
          id: z.string(),
          name: z.string(),
          owner: UserProfile,
        });

        export const updateUserProfileParams = z.object({
          profile: UserProfile,
        });

        export const updateUserProfileReturn = z.boolean();
      `;

			assert.strictEqual(
				normalizeWhitespace(zodSchema),
				normalizeWhitespace(expectedSchema),
				'Generated schema for custom-types.js does not match expected output'
			);
		});

		it('should warn about unknown types and default to z.any()', async () => {
			const sourceCode = `
        /**
         * @typedef {object} MyObject
         * @property {string} name
         * @property {SomeUnknownType} a - This type is not defined.
         */
      `;
			consoleWarnMock.mock.resetCalls(); // Reset call count before this test
			const { zodSchema } = await generate(sourceCode);

			const expectedSchema = `
        /**
         * This file was auto-generated by jsdoc-to-zod.
         * Do not make direct changes to this file.
         */

        import { z } from 'zod';

        export const MyObject = z.object({
          name: z.string(),
          a: z.any(),
        });
      `;

			assert.strictEqual(
				normalizeWhitespace(zodSchema),
				normalizeWhitespace(expectedSchema),
				'Schema with unknown type should default to z.any()'
			);

			// Verify that a warning was logged for the unknown type.
			assert.strictEqual(consoleWarnMock.mock.callCount(), 1, 'A warning should be logged for the unknown type');
			const [warningMessage] = consoleWarnMock.mock.calls[0].arguments;
			assert.ok(
				warningMessage.includes('Unknown type "SomeUnknownType"'),
				'The warning message should mention the unknown type name'
			);
		});
	});

	it('should handle malformed JSDoc gracefully by returning an empty result', async () => {
		// This JSDoc is malformed because of the unclosed brace.
		const malformedSource = `
      /**
       * @param {string
       */
      function doSomething(s) {}
    `;
		consoleWarnMock.mock.resetCalls();
		const { zodSchema } = await generate(malformedSource);

		assert.strictEqual(zodSchema, '', 'Should produce no schema for malformed JSDoc');
		assert.ok(consoleWarnMock.mock.callCount() > 0, 'Should warn about parsing errors in JSDoc');
	});

	it('should handle malformed JavaScript gracefully by throwing a specific error', async () => {
		const malformedJS = 'const a =;';
		await assert.rejects(
			generate(malformedJS, { filePath: 'malformed.js' }),
			(err) => {
				assert.strictEqual(err instanceof Error, true);
				assert.ok(
					err.message.startsWith('Acorn parsing error in malformed.js'),
					'Error message should indicate a parsing failure from Acorn'
				);
				return true;
			},
			'generate() should reject with a specific error for invalid JS syntax'
		);
	});
});