/**
 * @file src/generators/crontab-builder.js
 * @description Builds a valid crontab file string from an array of parsed schedule objects,
 * including headers and environment variables.
 */

/**
 * @typedef {import('../parsers/comment-extractor.js').CronSchedule} CronSchedule
 */

/**
 * A custom error class for crontab generation failures.
 */
class CrontabBuilderError extends Error {
  /**
   * @param {string} message The error message.
   * @param {object} [options] Additional options.
   * @param {Error} [options.cause] The original error that was caught.
   */
  constructor(message, options = {}) {
    super(message);
    this.name = 'CrontabBuilderError';
    if (options.cause) {
      this.cause = options.cause;
    }
  }
}

/**
 * Generates a standard header for the crontab file.
 * The header warns users against editing the file directly.
 *
 * @private
 * @param {string|null} customHeader - An optional custom header string to prepend.
 * @returns {string} The formatted header block.
 */
function generateHeader(customHeader) {
  const lines = [
    '# ============================================================================',
    '# DO NOT EDIT THIS FILE DIRECTLY!',
    '# This file is automatically generated by the "declarative-cron-parser" tool.',
    '# Changes will be overwritten on the next run.',
    '# To add or modify cron jobs, edit the @cron comments in your source files.',
    `# Generated on: ${new Date().toISOString()}`,
    '# ============================================================================',
  ];

  if (typeof customHeader === 'string' && customHeader.trim()) {
    return `${customHeader.trim()}\n\n${lines.join('\n')}`;
  }

  return lines.join('\n');
}

/**
 * Formats environment variables into a crontab-compatible string.
 *
 * @private
 * @param {Record<string, string>} envVars - An object where keys are variable names and values are their values.
 * @returns {string} A string of `KEY="VALUE"` pairs, each on a new line.
 * @throws {CrontabBuilderError} If envVars is not a valid object or contains invalid keys/values.
 */
function formatEnvironmentVariables(envVars) {
  if (envVars == null) { // Checks for both null and undefined
    return '';
  }
  if (typeof envVars !== 'object' || Array.isArray(envVars)) {
    throw new CrontabBuilderError('Environment variables must be provided as an object.');
  }

  const lines = [];
  const validKeyRegex = /^[a-zA-Z_][a-zA-Z0-9_]*$/;

  for (const [key, value] of Object.entries(envVars)) {
    if (!validKeyRegex.test(key)) {
      throw new CrontabBuilderError(`Invalid environment variable name: "${key}". Names must start with a letter or underscore, followed by letters, numbers, or underscores.`);
    }
    if (typeof value !== 'string' && typeof value !== 'number') {
      throw new CrontabBuilderError(`Value for environment variable "${key}" must be a string or number.`);
    }

    // Crontab requires special characters in values to be escaped, but quoting is a safer and more common practice.
    // We will enforce simple string/number values and quote them.
    const sanitizedValue = String(value).replace(/"/g, '\\"');
    lines.push(`${key}="${sanitizedValue}"`);
  }

  return lines.join('\n');
}

/**
 * Formats an array of CronSchedule objects into crontab job lines.
 *
 * @private
 * @param {CronSchedule[]} schedules - The array of parsed schedule objects.
 * @returns {string} A string containing all formatted cron job lines.
 * @throws {CrontabBuilderError} If schedules array is invalid or contains invalid entries.
 */
function formatCronJobs(schedules) {
  if (!Array.isArray(schedules)) {
    throw new CrontabBuilderError('Schedules must be provided as an array.');
  }

  const lines = schedules.map((job, index) => {
    if (
      !job ||
      typeof job.schedule !== 'string' ||
      typeof job.command !== 'string' ||
      typeof job.sourceFile !== 'string'
    ) {
      throw new CrontabBuilderError(`Invalid schedule object at index ${index}. It must contain 'schedule', 'command', and 'sourceFile' properties.`);
    }

    const comment = `# Source: ${job.sourceFile}:${job.sourceLine}`;
    const jobLine = `${job.schedule} ${job.command}`;
    return `${comment}\n${jobLine}`;
  });

  return lines.join('\n\n'); // Separate jobs with a blank line for readability
}

/**
 * Builds a complete crontab file as a string from a set of schedules and configuration options.
 *
 * @param {object} options - The configuration for building the crontab.
 * @param {CronSchedule[]} options.schedules - An array of parsed schedule objects.
 * @param {Record<string, string>} [options.env={}] - An object of environment variables to include at the top of the crontab.
 * @param {string|null} [options.header=null] - A custom string to be prepended before the default header.
 * @returns {string} The complete, formatted crontab file content.
 * @throws {CrontabBuilderError} If inputs are invalid or an error occurs during building.
 */
export function buildCrontab(options) {
  const { schedules = [], env = {}, header = null } = options ?? {};

  try {
    const headerBlock = generateHeader(header);
    const envBlock = formatEnvironmentVariables(env);
    const jobsBlock = formatCronJobs(schedules);

    const parts = [headerBlock];

    if (envBlock) {
      parts.push(envBlock);
    }

    if (jobsBlock) {
      parts.push(jobsBlock);
    }

    // Join the main blocks with double newlines for separation.
    // Add a trailing newline, which is required by many cron daemons.
    return parts.join('\n\n') + '\n';
  } catch (error) {
    if (error instanceof CrontabBuilderError) {
      throw error;
    }
    // Wrap unexpected errors for consistent error handling.
    throw new CrontabBuilderError('An unexpected error occurred during crontab generation.', { cause: error });
  }
}