/**
 * @file src/utils/constants.js
 * @description Exports shared constants used throughout the application.
 * This includes regular expressions for parsing, default file names, and other static values.
 */

/**
 * Regular expression to find environment variable access in code.
 *
 * This regex is designed to capture the variable name from three common patterns:
 * 1. Dot notation: `process.env.VAR_NAME`
 * 2. Bracket notation with single quotes: `process.env['VAR_NAME']`
 * 3. Bracket notation with double quotes: `process.env["VAR_NAME"]`
 *
 * Breakdown:
 * - `process\.env`: Matches the literal string "process.env".
 * - `(?: ... )`: A non-capturing group for the different access patterns.
 * - `\.([a-zA-Z_][a-zA-Z0-9_]*)`:
 *   - `\.`: Matches the dot in dot notation.
 *   - `([a-zA-Z_][a-zA-Z0-9_]*)`: Capturing group 1 for the variable name.
 *     - It must start with a letter or underscore.
 *     - It can be followed by letters, numbers, or underscores.
 * - `|`: OR operator.
 * - `\[['"]([a-zA-Z_][a-zA-Z0-9_]*)['"]\]`:
 *   - `\[`: Matches the opening bracket `[`.
 *   - `['"]`: Matches either a single or double quote.
 *   - `([a-zA-Z_][a-zA-Z0-9_]*)`: Capturing group 2 for the variable name (same pattern as above).
 *   - `['"]`: Matches the closing quote (must be the same as the opening one, but this simple regex doesn't enforce that, which is acceptable for this use case).
 *   - `\]`: Matches the closing bracket `]`.
 *
 * The `g` flag ensures it finds all matches in a file, not just the first one.
 * The two capturing groups mean a match will have the variable name in either `match[1]` or `match[2]`.
 */
export const ENV_VAR_REGEX = /process\.env\.(?:([a-zA-Z_][a-zA-Z0-9_]*))|process\.env\[['"]([a-zA-Z_][a-zA-Z0-9_]*)['"]\]/g;

/**
 * The default filename for the generated environment template file.
 * @type {string}
 */
export const DEFAULT_OUTPUT_FILE = '.env.template';

/**
 * The default glob pattern for files to include in the scan.
 * This pattern covers common source code directories and file extensions.
 * @type {string}
 */
export const DEFAULT_SOURCE_PATTERN = 'src/**/*.{js,jsx,ts,tsx}';

/**
 * An array of default glob patterns to ignore during the file scan.
 * This helps avoid scanning node_modules, build artifacts, and test files,
 * which can contain false positives or irrelevant variable usages.
 * @type {string[]}
 */
export const DEFAULT_IGNORE_PATTERNS = [
  'node_modules/**',
  'dist/**',
  'build/**',
  'coverage/**',
  '**/*.test.js',
  '**/*.spec.js',
];

/**
 * The header comment to be placed at the top of the generated .env.template file.
 * It provides context and instructions for developers using the template.
 * @type {string}
 */
export const TEMPLATE_HEADER = `# This file was auto-generated by env-template-generator.
# It contains a list of all environment variables used by the application.
#
# Populate this file with your environment-specific values and rename it to .env
# for local development. DO NOT commit the .env file to version control.
#
# Generated on: ${new Date().toISOString()}`;