/**
 * @fileoverview The main programmatic API for the JSDoc-to-Zod generator.
 * This file exports the core `generate` function, which orchestrates the
 * parsing and schema generation process for library use.
 * @author Your Name <you@example.com>
 * @license MIT
 * @project JSDoc to Zod Schema Generator
 */

import { parseJavaScript } from './parser/js-parser.js';
import { generateZodSchema, generateZodFileContent } from './generator/zod-generator.js';
import TypeResolver from './type-resolver.js';

/**
 * @typedef {object} GenerateOptions
 * @property {string} [filePath='<anonymous>'] - The path of the file being processed, used for error reporting and context.
 * @property {TypeResolver} [typeResolver] - An optional, pre-existing TypeResolver instance. If not provided, a new one will be created. This allows for resolving types across multiple files.
 */

/**
 * @typedef {object} GenerateResult
 * @property {string} zodSchema - The complete, formatted Zod schema file content as a string.
 * @property {TypeResolver} typeResolver - The TypeResolver instance used during generation, containing all discovered types.
 * @property {Array<{name: string, schema: string}>} schemas - An array of individual generated schemas.
 */

/**
 * Parses JavaScript source code, extracts JSDoc annotations, and generates
 * corresponding Zod validation schemas. This is the main entry point for
 * the library's programmatic API.
 *
 * @param {string} sourceCode - The JavaScript source code to process.
 * @param {GenerateOptions} [options={}] - Configuration options for the generation process.
 * @returns {Promise<GenerateResult>} A promise that resolves to an object containing the generated Zod schema string and other metadata.
 * @throws {Error} If the source code is invalid or a fatal error occurs during processing.
 *
 * @example
 * import { generate } from 'jsdoc-to-zod';
 * import fs from 'node:fs/promises';
 *
 * const jsCode = await fs.readFile('my-file.js', 'utf8');
 * const { zodSchema } = await generate(jsCode, { filePath: 'my-file.js' });
 * console.log(zodSchema);
 * // Output:
 * // /**
 * //  * This file was auto-generated by jsdoc-to-zod.
 * //  * Do not make direct changes to this file.
 * //  */
 * //
 * // import { z } from 'zod';
 * //
 * // export const MyType = z.object({ ... });
 */
export async function generate(sourceCode, options = {}) {
	if (typeof sourceCode !== 'string') {
		throw new TypeError('sourceCode must be a non-empty string.');
	}

	const { filePath = '<anonymous>', typeResolver = new TypeResolver() } = options;

	try {
		// 1. Parse the JavaScript source to find all JSDoc blocks and their associated code.
		const foundDocs = parseJavaScript(sourceCode, filePath);
		if (foundDocs.length === 0) {
			return {
				zodSchema: '',
				typeResolver,
				schemas: [],
			};
		}

		// 2. First Pass: Register all `@typedef` types in the TypeResolver.
		// This builds a map of all custom types available in the source code,
		// allowing them to be referenced before they are generated.
		for (const doc of foundDocs) {
			if (doc.parsed.isTypeDef && doc.parsed.name) {
				typeResolver.register(doc.parsed.name, doc.parsed);
			}
		}

		// 3. Second Pass: Generate Zod schemas for all found JSDoc blocks.
		// This includes `@typedef` types, function parameters/returns, and other annotated constructs.
		const generatedSchemas = [];
		for (const doc of foundDocs) {
			// The `generateZodSchema` function will use the typeResolver to look up
			// custom types when it encounters them.
			const schemaString = generateZodSchema(doc.parsed, typeResolver);

			if (schemaString) {
				generatedSchemas.push({
					name: doc.name,
					schema: schemaString,
				});
			}
		}

		// 4. Combine all individual schemas into a single file content string.
		// This adds the necessary `import { z } from 'zod';` header.
		const finalZodSchema = generateZodFileContent(generatedSchemas);

		return {
			zodSchema: finalZodSchema,
			typeResolver,
			schemas: generatedSchemas,
		};
	} catch (error) {
		console.error(`[jsdoc-to-zod] An error occurred while processing ${filePath}:`, error);
		// Re-throw the error to allow the calling context (e.g., CLI) to handle it.
		throw error;
	}
}