#!/usr/bin/env node

/**
 * This is an auto-generated file by jsdoc-to-cli.
 * DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Your changes will be overwritten on the next run.
 */

import { Command } from 'commander';
import * as module0 from './math-functions.js';

/**
 * Main function to set up and run the CLI.
 */
async function main() {
  const program = new Command();

  program
    .name('cli') // Note: This will be replaced by the binary name in package.json.
    .description('A collection of example mathematical functions.')
    .version('1.0.0');

  // --- Command Definitions ---
  program.command('add')
    .description('Adds two numbers and returns the sum. This is the primary command and demonstrates basic argument handling.')
    .argument('<number>', 'The first number to add.')
    .argument('<number>', 'The second number to add.')
    .action(async (a, b, options) => {
      // Call the original function from the imported module.
      const result = await module0.add(a, b);

      // Log the result to stdout if it's not undefined.
      // This allows functions with no return value to execute silently.
      if (result !== undefined) {
        // For objects/arrays, pretty-print. For others, convert to string.
        if (typeof result === 'object' && result !== null) {
          console.log(JSON.stringify(result, null, 2));
        } else {
          console.log(String(result));
        }
      }
    })

  program.command('multiply')
    .description('Multiplies a list of numbers. This function demonstrates handling multiple arguments and optional flags.')
    .argument('<numbers...>', 'A list of numbers to multiply together.')
    .option('--log', 'If true, prints the result to the console with a label.')
    .option('--prefix <value>', 'A prefix string to use when logging the result.', 'Result:')
    .action(async (numbers, options) => {
      // Call the original function from the imported module.
      const result = await module0.multiply(numbers, options);

      // Log the result to stdout if it's not undefined.
      // This allows functions with no return value to execute silently.
      if (result !== undefined) {
        // For objects/arrays, pretty-print. For others, convert to string.
        if (typeof result === 'object' && result !== null) {
          console.log(JSON.stringify(result, null, 2));
        } else {
          console.log(String(result));
        }
      }
    })

  program.command('power')
    .description('Calculates the power of a number. This demonstrates a required argument and an optional argument with a default value.')
    .argument('<number>', 'The base number.')
    .option('--exponent <number>', 'The exponent to raise the base to.', '2')
    .action(async (base, options) => {
      // Call the original function from the imported module.
      const result = await module0.power(base, options.exponent);

      // Log the result to stdout if it's not undefined.
      // This allows functions with no return value to execute silently.
      if (result !== undefined) {
        // For objects/arrays, pretty-print. For others, convert to string.
        if (typeof result === 'object' && result !== null) {
          console.log(JSON.stringify(result, null, 2));
        } else {
          console.log(String(result));
        }
      }
    })

  program.command('greet')
    .description('Greets a user. This function does not return a value. The generated CLI command should simply execute and exit silently.')
    .argument('<string>', 'The name of the person to greet.')
    .action(async (name, options) => {
      // Call the original function from the imported module.
      const result = await module0.greet(name);

      // Log the result to stdout if it's not undefined.
      // This allows functions with no return value to execute silently.
      if (result !== undefined) {
        // For objects/arrays, pretty-print. For others, convert to string.
        if (typeof result === 'object' && result !== null) {
          console.log(JSON.stringify(result, null, 2));
        } else {
          console.log(String(result));
        }
      }
    })

  // Handle cases where no command is specified.
  if (!process.argv.slice(2).length) {
    program.outputHelp();
    process.exit(1);
  }

  try {
    await program.parseAsync(process.argv);
  } catch (error) {
    // Gracefully handle errors from command actions.
    // Commander's own error handling (e.g., for missing args) is usually sufficient,
    // but this catches errors thrown from within the imported functions.
    console.error(`[Error] ${error.message}`);
    process.exit(1);
  }
}

main();