/**
 * @fileoverview Utility functions for parsing JSDoc doclet objects.
 *
 * This module provides a set of pure functions designed to extract structured
 * information from the raw doclet objects generated by the `jsdoc-api`. It
 * handles the logic for identifying commands, parsing parameters into arguments
 * and options, and cleaning up the extracted data for use in the command builder.
 *
 * @module src/utils/doclet-parser
 * @see {@link https://jsdoc.app/about-ast-nodes.html} for doclet structure.
 */

/**
 * A regular expression to parse JSDoc parameter types and names.
 * It handles optional parameters `[name]`, default values `[name=defaultValue]`,
 * and destructuring `[{prop1, prop2}]`.
 *
 * Groups:
 * 1. Type: `{string}`
 * 2. Name: `name`, `[name]`, `[name=value]`, `[{prop}]`
 */
const PARAM_REGEX = /^\s*\{(.*)}\s+(.*)\s*$/;

/**
 * A regular expression to parse the name part of a JSDoc parameter,
 * specifically to extract the name and default value from optional parameters.
 *
 * Groups:
 * 1. Name: The core name of the parameter.
 * 2. Default Value: The default value, if specified.
 */
const OPTIONAL_PARAM_REGEX = /^\[(.+?)(?:=(.*))?]$/;

/**
 * A regular expression to clean up default values, removing surrounding quotes.
 */
const DEFAULT_VALUE_CLEANUP_REGEX = /^['"](.*)['"]$/;

/**
 * A regular expression to check if a parameter name indicates destructuring.
 */
const DESTRUCTURING_REGEX = /[{[].*[}\]]/;

/**
 * Normalizes a JSDoc type string to a simpler, more consistent format.
 *
 * @param {string} typeString - The raw type string from JSDoc (e.g., "string", "Number", "boolean|string").
 * @returns {string} A normalized, lowercase type string (e.g., "string", "number", "boolean").
 *                   Defaults to "string" if the type is complex or undefined.
 */
function normalizeType(typeString = '') {
  const normalized = (typeString || '').toLowerCase().trim();

  // For unions like `string|number`, we prefer a specific order.
  if (normalized.includes('string')) return 'string';
  if (normalized.includes('number')) return 'number';
  if (normalized.includes('boolean')) return 'boolean';

  // If no recognizable primitive is found, default to string.
  // This is a safe bet for CLI arguments.
  return 'string';
}

/**
 * Parses a single JSDoc `@param` tag object into a structured parameter definition.
 *
 * @param {object} paramTag - The JSDoc tag object for a single parameter.
 * @property {string} paramTag.type.names - Array of type names (e.g., ['string']).
 * @property {string} paramTag.name - The name of the parameter (e.g., 'message', '[count=1]').
 * @property {string} paramTag.description - The description of the parameter.
 * @property {boolean} [paramTag.optional] - Indicates if the parameter is optional.
 * @property {*} [paramTag.defaultvalue] - The default value.
 * @returns {object|null} A structured object representing the parameter, or null if parsing fails.
 *   The object contains `name`, `type`, `description`, `required`, and `defaultValue`.
 */
function parseParamTag(paramTag) {
  if (!paramTag || !paramTag.name) {
    return null;
  }

  const { name, description = '', type } = paramTag;
  const isOptional = paramTag.optional === true;
  let paramName = name;
  let defaultValue = paramTag.defaultvalue;

  // JSDoc's `optional` and `defaultvalue` properties are reliable.
  // We can trust them over regex parsing if they exist.
  if (isOptional && OPTIONAL_PARAM_REGEX.test(name)) {
    const match = name.match(OPTIONAL_PARAM_REGEX);
    if (match) {
      paramName = match[1];
      // `paramTag.defaultvalue` is more reliable, but fallback to regex.
      if (defaultValue === undefined && match[2] !== undefined) {
        defaultValue = match[2].replace(DEFAULT_VALUE_CLEANUP_REGEX, '$1');
      }
    }
  }

  // Avoid using destructuring patterns as parameter names.
  if (DESTRUCTURING_REGEX.test(paramName)) {
    console.warn(
      `[Warning] Skipping parameter with destructuring: "${name}". Destructured parameters are not supported.`
    );
    return null;
  }

  // `type.names` is an array, e.g., ['string', 'number'] for a union.
  // We'll simplify this to a single representative type.
  const rawType = type?.names?.join('|') || 'string';

  return {
    name: paramName,
    type: normalizeType(rawType),
    description: description.trim(),
    required: !isOptional,
    defaultValue: defaultValue,
  };
}

/**
 * Parses a function doclet to extract information needed to build a CLI command.
 *
 * @param {object} doclet - A single doclet object from `jsdoc-api`.
 * @returns {object|null} A structured command definition object or null if the doclet
 *   is not a valid, exported function with a JSDoc block. The object contains:
 *   - `name` {string}: The function name, used as the command name.
 *   - `description` {string}: The function description, used for command help.
 *   - `longname` {string}: The fully qualified name of the function.
 *   - `params` {Array<object>}: An array of parsed parameter objects.
 */
export function parseFunctionDoclet(doclet) {
  // A valid command must be a function, have a JSDoc block, and be exported.
  if (
    !doclet ||
    doclet.kind !== 'function' ||
    doclet.undocumented ||
    doclet.access === 'private' ||
    !doclet.name ||
    doclet.memberof // Skip class methods for now
  ) {
    return null;
  }

  const params = (doclet.params || [])
    .map(parseParamTag)
    .filter(p => p !== null); // Filter out any unparseable or skipped params

  return {
    name: doclet.name,
    description: (doclet.description || '').trim(),
    longname: doclet.longname,
    params,
  };
}

/**
 * Analyzes an array of doclets and extracts all valid command definitions.
 *
 * @param {Array<object>} doclets - An array of doclet objects from `jsdoc-api`.
 * @returns {Array<object>} An array of command definition objects, ready for the command builder.
 */
export function findCommands(doclets) {
  if (!Array.isArray(doclets)) {
    return [];
  }

  return doclets
    .map(parseFunctionDoclet)
    .filter(command => command !== null);
}