/**
 * @file index.js
 * @description Main entry point for programmatic usage of the jsdoc-to-zod library.
 * This file exports the core functions, allowing developers to integrate JSDoc-to-Zod
 * generation directly into their own applications and build tools.
 */

import { promises as fs } from 'node:fs';
import { parseAST } from './src/parser/ast-parser.js';
import { generateZodSchemaFile } from './src/generator/zod-builder.js';
import { processFile } from './src/processor.js';

/**
 * Generates Zod schema definitions from a string of JavaScript source code.
 *
 * This is the primary function for programmatic use when the source code is already
 * available in memory. It parses the code, extracts JSDoc annotations, and builds
 * the corresponding Zod schemas.
 *
 * @param {string} sourceCode - The JavaScript source code to process.
 * @param {object} [options] - Configuration options for generation.
 * @param {boolean} [options.includeHeader=true] - Whether to include the standard
 *   `import { z } from 'zod';` header in the output. Set to `false` if you are
 *   concatenating multiple results.
 * @returns {Promise<string>} A promise that resolves to a string containing the
 *   generated Zod schemas. Returns an empty string if no convertible JSDoc
 *   annotations are found.
 * @throws {Error} Throws an error if the source code is invalid or parsing fails.
 *
 * @example
 * import { generate } from 'jsdoc-to-zod';
 *
 * const jsCode = `
 * /**
 *  * @param {string} name - The user's name.
 *  * @param {number} [age] - The user's age.
 *  *\/
 * function processUser(name, age) {
 *   // ...
 * }`;
 *
 * const zodSchema = await generate(jsCode);
 * console.log(zodSchema);
 * // Output:
 * // /**
 * //  * This file was generated by jsdoc-to-zod.
 * //  * Do not make changes to this file directly.
 * //  *\/
 * //
 * // import { z } from 'zod';
 * //
 * // // Generated from processUser
 * // export const processUserSchema = z.object({
 * //   name: z.string().describe('The user\'s name.'),
 * //   age: z.number().optional().describe('The user\'s age.')
 * // });
 */
export async function generate(sourceCode, options = {}) {
  const { includeHeader = true } = options;

  if (typeof sourceCode !== 'string') {
    throw new Error('Invalid input: sourceCode must be a string.');
  }

  // The `parseAST` function is synchronous, but we keep this API async
  // for future-proofing and consistency with `generateFromFile`.
  try {
    const parsedEntities = parseAST(sourceCode);

    if (parsedEntities.length === 0) {
      return '';
    }

    const schemaContent = generateZodSchemaFile(parsedEntities);

    if (!includeHeader) {
      // The generator includes the header by default. We can remove it if requested.
      // This is a simple way to achieve this without complicating the generator.
      const lines = schemaContent.split('\n');
      const headerEndIndex = lines.findIndex(line => line.includes("import { z } from 'zod';"));
      if (headerEndIndex !== -1) {
        // Slice after the import line and any blank lines that follow.
        return lines.slice(headerEndIndex + 2).join('\n');
      }
    }

    return schemaContent;
  } catch (error) {
    // Re-throw errors from parsing or generation with a clearer top-level message.
    throw new Error(`Failed to generate schemas from source code. Reason: ${error.message}`, { cause: error });
  }
}

/**
 * Generates Zod schema definitions by reading and processing a JavaScript file.
 *
 * This function is a convenient wrapper around `generate` for file-based workflows.
 * It reads the file content and then uses the same core logic to produce the schemas.
 *
 * @param {string} filePath - The path to the JavaScript file to process.
 * @param {object} [options] - Configuration options for generation. See `generate` function for details.
 * @returns {Promise<string>} A promise that resolves to a string containing the
 *   generated Zod schemas. Returns an empty string if the file contains no
 *   convertible JSDoc annotations.
 * @throws {Error} Throws an error if the file cannot be read or if processing fails.
 *
 * @example
 * import { generateFromFile } from 'jsdoc-to-zod';
 *
 * const zodSchema = await generateFromFile('./path/to/my-file.js');
 * console.log(zodSchema);
 */
export async function generateFromFile(filePath, options = {}) {
  if (typeof filePath !== 'string' || !filePath) {
    throw new Error('Invalid input: filePath must be a non-empty string.');
  }

  try {
    // The `processFile` function from `src/processor.js` already handles
    // reading the file and generating the schema string. We can reuse it directly.
    const { zodSchema } = await processFile(filePath);

    // Handle the `includeHeader` option, similar to the `generate` function.
    if (options.includeHeader === false) {
      const lines = zodSchema.split('\n');
      const headerEndIndex = lines.findIndex(line => line.includes("import { z } from 'zod';"));
      if (headerEndIndex !== -1) {
        return lines.slice(headerEndIndex + 2).join('\n');
      }
    }

    return zodSchema;
  } catch (error) {
    // The processor already adds context, so we can just re-throw.
    throw error;
  }
}

// Default export for convenience, exposing the core functions.
export default {
  generate,
  generateFromFile,
};