/**
 * @fileoverview Orchestrates the generation of the CLI script.
 *
 * This module contains the main logic for the jsdoc-to-cli generator. It
 * coordinates the process of finding source files, parsing JSDoc comments,
 * building command definitions, and writing the final, executable CLI script
 * to disk. It serves as the central hub connecting the file system, JSDoc
 * parser, command builder, and template engine.
 *
 * @module src/core/generator
 */

import path from 'node:path';
import fs from 'node:fs/promises';
import jsdoc from 'jsdoc-api';
import { findFiles } from '../utils/file-finder.js';
import { findCommands } from '../utils/doclet-parser.js';
import { buildCommandSnippet } from './command-builder.js';
import { generateCliContent } from '../templates/cli-template.js';

/**
 * Parses JSDoc from a list of files and returns the doclet data.
 *
 * This function uses the `jsdoc-api` library to parse the provided JavaScript
 * files. It filters out undocumented symbols to focus only on those with
* JSDoc comments.
 *
 * @param {string[]} filePaths - An array of absolute paths to the JavaScript files to parse.
 * @returns {Promise<object[]>} A promise that resolves to an array of JSDoc doclet objects.
 * @throws {Error} If `jsdoc-api` fails to parse the files.
 */
async function parseJsdoc(filePaths) {
  if (!Array.isArray(filePaths) || filePaths.length === 0) {
    return [];
  }

  try {
    const doclets = await jsdoc.explain({ files: filePaths });
    // Filter out doclets that are undocumented or from external sources (like node_modules).
    return doclets.filter(d => !d.undocumented && d.meta);
  } catch (error) {
    console.error(`[Error] Failed to parse JSDoc from files: ${filePaths.join(', ')}`);
    throw new Error(`JSDoc parsing failed: ${error.message}`);
  }
}

/**
 * Reads the project's package.json to extract metadata like version and description.
 *
 * This function safely reads and parses the `package.json` file from the specified
 * project root. It provides default values if the file or specific fields are missing.
 *
 * @param {string} projectRoot - The root directory of the project, where package.json is located.
 * @returns {Promise<{version: string, description: string}>} An object containing the project's version and description.
 */
async function getProjectMetadata(projectRoot) {
  const pkgPath = path.join(projectRoot, 'package.json');
  const defaults = {
    version: '1.0.0',
    description: 'A CLI generated by jsdoc-to-cli.',
  };

  try {
    const pkgContent = await fs.readFile(pkgPath, 'utf-8');
    const pkg = JSON.parse(pkgContent);
    return {
      version: pkg.version ?? defaults.version,
      description: pkg.description ?? defaults.description,
    };
  } catch (error) {
    // If package.json doesn't exist or is invalid, just use defaults.
    // This is not a critical error, so we warn instead of throwing.
    if (error.code !== 'ENOENT') {
      console.warn(`[Warning] Could not read or parse package.json at ${pkgPath}. Using default values.`);
    }
    return defaults;
  }
}

/**
 * Generates and writes the CLI file to the specified output path.
 *
 * This is the main orchestrator function. It takes configuration options,
 * finds files, parses them, builds command snippets, and uses the template
 * to generate the final CLI script, which is then written to the filesystem.
 *
 * @param {object} options - The configuration options for the generator.
 * @param {string[]} options.input - An array of glob patterns for input files.
 * @param {string} options.output - The path where the generated CLI file will be written.
 * @param {string} [options.cwd=process.cwd()] - The current working directory for resolving paths.
 * @returns {Promise<void>} A promise that resolves when the CLI file has been successfully written.
 * @throws {Error} If any step of the generation process fails (e.g., file I/O, parsing).
 */
export async function generateCli({ input, output, cwd = process.cwd() }) {
  if (!input || !output) {
    throw new Error('Both "input" and "output" options are required.');
  }

  const absoluteOutputPath = path.resolve(cwd, output);
  const outputDir = path.dirname(absoluteOutputPath);

  // 1. Find all source files based on glob patterns.
  console.log(`🔍 Searching for files matching: ${input.join(', ')}`);
  const filePaths = await findFiles(input, { cwd });
  if (filePaths.length === 0) {
    console.warn('[Warning] No input files found. The generated CLI will have no commands.');
  } else {
    console.log(`✅ Found ${filePaths.length} file(s).`);
  }

  // 2. Parse JSDoc from the found files.
  console.log('📝 Parsing JSDoc comments...');
  const allDoclets = await parseJsdoc(filePaths);

  // 3. Extract command definitions from doclets.
  const commands = findCommands(allDoclets);
  if (commands.length === 0) {
    console.warn('[Warning] No JSDoc-annotated functions found to generate commands.');
  } else {
    console.log(`✅ Identified ${commands.length} function(s) to expose as CLI commands.`);
  }

  // 4. Build command snippets for each command.
  // We need to map each command back to its original file to generate correct import paths.
  const fileMap = new Map(filePaths.map((p, i) => [p, i]));
  const commandSnippets = commands.map(command => {
    const filePath = path.resolve(command.longname.split('~')[0]); // longname includes file path
    const moduleIndex = fileMap.get(filePath);
    if (moduleIndex === undefined) {
      // This should theoretically not happen if logic is sound.
      throw new Error(`Could not find module index for command "${command.name}" from file "${filePath}".`);
    }
    return buildCommandSnippet(command, moduleIndex);
  });

  // 5. Prepare data for the template.
  const importPaths = filePaths.map(p => path.relative(outputDir, p).replace(/\\/g, '/'));
  const { version, description } = await getProjectMetadata(cwd);

  const templateData = {
    programVersion: version,
    programDescription: description,
    importPaths,
    commandSnippets,
  };

  // 6. Generate the final CLI script content.
  const cliContent = generateCliContent(templateData);

  // 7. Write the script to the output file.
  console.log(`✍️ Writing generated CLI to: ${absoluteOutputPath}`);
  try {
    await fs.mkdir(outputDir, { recursive: true });
    await fs.writeFile(absoluteOutputPath, cliContent, 'utf-8');
    // Make the generated file executable.
    await fs.chmod(absoluteOutputPath, 0o755);
  } catch (error) {
    console.error(`[Error] Failed to write CLI file to ${absoluteOutputPath}`);
    throw new Error(`File write failed: ${error.message}`);
  }

  console.log('🚀 CLI generation complete!');
}