/**
 * @file src/parser/ast-walker.js
 * @description Core logic for traversing an AST to find environment variable usages.
 * This module uses `acorn-walk` to efficiently visit nodes in the AST generated
 * from a source file and identifies `process.env` access patterns.
 */

import { simple } from 'acorn-walk';
import { AST_NODE_TYPES, AST_IDENTIFIERS } from '../utils/constants.js';

/**
 * Checks if an AST node represents the `process.env` object.
 * It verifies that the node is a MemberExpression (`process.env`) where:
 * - `object` is an Identifier named 'process'.
 * - `property` is an Identifier named 'env'.
 *
 * @param {object} node - The AST node to inspect.
 * @returns {boolean} - True if the node represents `process.env`, false otherwise.
 */
const isProcessEnv = (node) => {
  if (!node || node.type !== AST_NODE_TYPES.MEMBER_EXPRESSION) {
    return false;
  }

  const { object, property } = node;

  return (
    object.type === AST_NODE_TYPES.IDENTIFIER &&
    object.name === AST_IDENTIFIERS.PROCESS &&
    property.type === AST_NODE_TYPES.IDENTIFIER &&
    property.name === AST_IDENTIFIERS.ENV
  );
};

/**
 * Traverses a given Abstract Syntax Tree (AST) to find all static references
 * to environment variables via `process.env`.
 *
 * It identifies two main patterns:
 * 1. Member Expression: `process.env.VAR_NAME`
 * 2. Computed Member Expression with a literal: `process.env['VAR_NAME']`
 *
 * Dynamic access patterns like `process.env[variable]` are ignored to prevent
 * false positives and ensure only statically defined variables are captured.
 *
 * @param {object} ast - The Abstract Syntax Tree object generated by Acorn.
 * @returns {Array<object>} An array of objects, each representing a found
 *   environment variable usage. Each object contains:
 *   - `name` (string): The name of the environment variable.
 *   - `loc` (object): The location object from the AST node, containing
 *     `start` and `end` line/column information.
 */
export const findEnvVarExpressions = (ast) => {
  if (!ast || typeof ast !== 'object') {
    // Defensive check for a valid AST object.
    return [];
  }

  const foundVars = [];

  // Use acorn-walk's `simple` walker for performance. We are only interested
  // in MemberExpression nodes, as they are the syntax for property access.
  simple(ast, {
    MemberExpression(node) {
      // We are looking for expressions like `(process.env).VAR_NAME` or `(process.env)['VAR_NAME']`.
      // The `object` part of this expression must be `process.env`.
      if (!isProcessEnv(node.object)) {
        return;
      }

      const { property, computed } = node;

      // Case 1: Member Expression (dot notation) -> `process.env.VAR_NAME`
      // `computed` is false, and `property` is an Identifier.
      if (!computed && property.type === AST_NODE_TYPES.IDENTIFIER) {
        foundVars.push({
          name: property.name,
          loc: node.loc,
        });
        return;
      }

      // Case 2: Computed Member Expression (bracket notation) -> `process.env['VAR_NAME']`
      // `computed` is true, and `property` is a Literal (a string).
      // We only care about string literals to avoid dynamic keys like `process.env[varName]`.
      if (computed && property.type === AST_NODE_TYPES.LITERAL && typeof property.value === 'string') {
        // Ensure the literal value is not an empty string.
        if (property.value.trim().length > 0) {
          foundVars.push({
            name: property.value,
            loc: node.loc,
          });
        }
      }
      // Other cases (e.g., dynamic access `process.env[varName]`) are implicitly ignored.
    },
  });

  return foundVars;
};