/**
 * @file src/world/map.js
 * @description Represents the static dungeon layout (walls, floors) and provides traversal utilities.
 * This class encapsulates the grid data generated by the DungeonGenerator and offers
 * a clean, safe API for other systems (like pathfinding and actor movement) to query
 * the map's properties without needing to know about the underlying grid structure.
 */

import { TILE_FLOOR } from './dungeon-generator.js';

/**
 * Manages the static dungeon map data, including the tile grid and room information.
 * It provides methods for checking tile properties (e.g., walkability) and finding
 * valid locations within the map.
 */
export class DungeonMap {
  /**
   * The 2D array representing the map's tiles.
   * @private
   * @type {number[][]}
   */
  #grid;

  /**
   * An array of room definitions, each with an ID and rectangle.
   * @private
   * @type {Array<{id: string, rect: {x: number, y: number, width: number, height: number}}>}
   */
  #rooms;

  /**
   * The width of the map in tiles.
   * @private
   * @type {number}
   */
  #width;

  /**
   * The height of the map in tiles.
   * @private
   * @type {number}
   */
  #height;

  /**
   * The initial spawn point for players.
   * @private
   * @type {{x: number, y: number}}
   */
  #startPosition;

  /**
   * Creates a new DungeonMap instance.
   * This constructor is intended to be called with the output of the DungeonGenerator.
   *
   * @param {object} mapData - The data to initialize the map.
   * @param {number[][]} mapData.grid - The 2D array of tiles (e.g., TILE_WALL, TILE_FLOOR).
   * @param {Array<object>} mapData.rooms - An array of room objects with their rectangular bounds.
   * @param {{x: number, y: number}} mapData.startPosition - The starting coordinates for players.
   */
  constructor({ grid, rooms, startPosition }) {
    if (!grid || !Array.isArray(grid) || grid.length === 0 || !Array.isArray(grid[0])) {
      throw new Error('Invalid map data: "grid" must be a non-empty 2D array.');
    }
    if (!rooms || !Array.isArray(rooms)) {
      throw new Error('Invalid map data: "rooms" must be an array.');
    }
    if (!startPosition || typeof startPosition.x !== 'number' || typeof startPosition.y !== 'number') {
      throw new Error('Invalid map data: "startPosition" must be an object with x and y coordinates.');
    }

    this.#grid = grid;
    this.#rooms = rooms;
    this.#startPosition = startPosition;
    this.#height = grid.length;
    this.#width = grid[0].length;
  }

  /**
   * Gets the width of the map.
   * @returns {number} The map width.
   */
  get width() {
    return this.#width;
  }

  /**
   * Gets the height of the map.
   * @returns {number} The map height.
   */
  get height() {
    return this.#height;
  }

  /**
   * Gets the designated start position for new players.
   * @returns {{x: number, y: number}} The start coordinates.
   */
  get startPosition() {
    // Return a copy to prevent external mutation
    return { ...this.#startPosition };
  }

  /**
   * Gets a copy of the room data.
   * @returns {Array<{id: string, rect: {x: number, y: number, width: number, height: number}}>} A list of rooms.
   */
  get rooms() {
    // Return a deep copy to ensure the original room data is immutable.
    return structuredClone(this.#rooms);
  }

  /**
   * Checks if a given coordinate is within the map boundaries.
   *
   * @param {number} x - The x-coordinate.
   * @param {number} y - The y-coordinate.
   * @returns {boolean} True if the coordinate is within bounds, false otherwise.
   */
  isInBounds(x, y) {
    return x >= 0 && x < this.#width && y >= 0 && y < this.#height;
  }

  /**
   * Checks if a tile at a given coordinate is walkable.
   * A tile is walkable if it is within the map bounds and is a floor tile.
   *
   * @param {number} x - The x-coordinate of the tile to check.
   * @param {number} y - The y-coordinate of the tile to check.
   * @returns {boolean} True if the tile is walkable, false otherwise.
   */
  isWalkable(x, y) {
    if (!this.isInBounds(x, y)) {
      return false;
    }
    return this.#grid[y][x] === TILE_FLOOR;
  }

  /**
   * Retrieves the type of tile at a specific coordinate.
   *
   * @param {number} x - The x-coordinate.
   * @param {number} y - The y-coordinate.
   * @returns {number | null} The tile type (e.g., TILE_FLOOR, TILE_WALL), or null if out of bounds.
   */
  getTile(x, y) {
    if (!this.isInBounds(x, y)) {
      return null;
    }
    return this.#grid[y][x];
  }

  /**
   * Finds a random walkable tile within the entire map.
   * This is useful for placing entities in random locations.
   * It will make a limited number of attempts to find a suitable tile.
   *
   * @param {number} [maxAttempts=100] - The maximum number of tries to find a walkable tile.
   * @returns {{x: number, y: number} | null} The coordinates of a random walkable tile, or null if none could be found.
   */
  getRandomWalkableTile(maxAttempts = 100) {
    for (let i = 0; i < maxAttempts; i++) {
      const x = Math.floor(Math.random() * this.#width);
      const y = Math.floor(Math.random() * this.#height);
      if (this.isWalkable(x, y)) {
        return { x, y };
      }
    }
    // Could not find a walkable tile after maxAttempts.
    // This is unlikely in a typical dungeon but handled defensively.
    return null;
  }

  /**
   * Finds a random walkable tile within a specific room.
   *
   * @param {string} roomId - The ID of the room to search within.
   * @param {number} [maxAttempts=100] - The maximum number of tries.
   * @returns {{x: number, y: number} | null} The coordinates of a random walkable tile in the room, or null.
   */
  getRandomWalkableTileInRoom(roomId, maxAttempts = 100) {
    const room = this.#rooms.find(r => r.id === roomId);
    if (!room) {
      console.warn(`Attempted to find tile in non-existent room ID: ${roomId}`);
      return null;
    }

    const { x: roomX, y: roomY, width: roomWidth, height: roomHeight } = room.rect;

    for (let i = 0; i < maxAttempts; i++) {
      const x = roomX + Math.floor(Math.random() * roomWidth);
      const y = roomY + Math.floor(Math.random() * roomHeight);

      // The check `isWalkable` is technically redundant if rooms are guaranteed to be floors,
      // but it provides an extra layer of safety.
      if (this.isWalkable(x, y)) {
        return { x, y };
      }
    }
    return null;
  }

  /**
   * Serializes the map data into a plain JavaScript object suitable for JSON conversion.
   * This is used for persisting the world state.
   *
   * @returns {{grid: number[][], rooms: Array<object>, startPosition: {x: number, y: number}}} A serializable representation of the map.
   */
  serialize() {
    return {
      grid: this.#grid,
      rooms: this.#rooms,
      startPosition: this.#startPosition,
    };
  }

  /**
   * Creates a DungeonMap instance from serialized data.
   * This is the counterpart to the `serialize` method, used when loading a saved state.
   *
   * @param {object} data - The serialized map data.
   * @returns {DungeonMap} A new DungeonMap instance.
   */
  static deserialize(data) {
    if (!data || !data.grid || !data.rooms || !data.startPosition) {
      throw new Error('Cannot deserialize map: data is malformed or incomplete.');
    }
    return new DungeonMap(data);
  }
}