/**
 * @file src/core.js
 * @description Core encryption and decryption logic for the Basic Auth Obfuscator.
 *
 * This module provides the fundamental cryptographic functions (`encrypt` and `decrypt`)
 * using Node.js's native `crypto` module. It is designed to be a self-contained,
 * zero-dependency unit that can be used both by the CLI and as a library in other
 * applications.
 */

import { createCipheriv, createDecipheriv, randomBytes, scrypt } from 'node:crypto';
import { promisify } from 'node:util';
import {
  ALGORITHM,
  IV_LENGTH,
  AUTH_TAG_LENGTH,
  KEY_LENGTH,
  ENCODING,
} from './constants.js';

// Promisify the scrypt function for async/await usage.
const scryptAsync = promisify(scrypt);

/**
 * Derives a 32-byte cryptographic key from a user-provided secret string using scrypt.
 * Scrypt is a password-based key derivation function (KDF) that is computationally
 * intensive, making it resistant to brute-force attacks.
 *
 * @param {string} secret - The user-provided secret string.
 * @param {Buffer} salt - A cryptographically secure salt.
 * @returns {Promise<Buffer>} A promise that resolves to the 32-byte derived key.
 * @throws {Error} If the secret is not a non-empty string.
 */
async function deriveKey(secret, salt) {
  if (typeof secret !== 'string' || secret.length === 0) {
    throw new Error('Invalid secret: must be a non-empty string.');
  }

  // The scrypt parameters (N, r, p) are chosen to be reasonably secure for
  // interactive use without being excessively slow.
  // N=16384 (2^14), r=8, p=1 are common defaults.
  const key = await scryptAsync(secret, salt, KEY_LENGTH, {
    N: 16384,
    r: 8,
    p: 1,
  });
  return key;
}

/**
 * Encrypts a plaintext string using AES-256-GCM.
 *
 * The process involves:
 * 1. Generating a random salt for key derivation.
 * 2. Deriving a 32-byte encryption key from the user secret and the salt using scrypt.
 * 3. Generating a random Initialization Vector (IV).
 * 4. Encrypting the plaintext using the derived key and IV.
 * 5. Concatenating the salt, IV, authentication tag, and ciphertext into a single buffer.
 * 6. Encoding the combined buffer as a URL-safe Base64 string.
 *
 * @param {string} plaintext - The string to encrypt (e.g., "user:pass").
 * @param {string} secret - The secret key string for encryption.
 * @returns {Promise<string>} A promise that resolves to the URL-safe Base64 encoded token.
 * @throws {Error} If input validation fails or encryption fails.
 */
export async function encrypt(plaintext, secret) {
  if (typeof plaintext !== 'string' || plaintext.length === 0) {
    throw new Error('Plaintext to encrypt cannot be empty.');
  }
  if (typeof secret !== 'string' || secret.length === 0) {
    throw new Error('Encryption secret cannot be empty.');
  }

  try {
    // 1. Generate a random salt for each encryption. This is crucial for security.
    const salt = randomBytes(16);

    // 2. Derive the encryption key.
    const key = await deriveKey(secret, salt);

    // 3. Generate a unique, random Initialization Vector (IV) for each encryption.
    const iv = randomBytes(IV_LENGTH);

    // 4. Create the AES-256-GCM cipher.
    const cipher = createCipheriv(ALGORITHM, key, iv);

    // 5. Encrypt the plaintext.
    const encrypted = Buffer.concat([cipher.update(plaintext, ENCODING), cipher.final()]);

    // 6. Get the authentication tag. This is essential for GCM's integrity check.
    const authTag = cipher.getAuthTag();

    // 7. Concatenate all parts: salt, iv, authTag, and the encrypted data.
    // This structure allows the decrypt function to easily parse the components.
    const tokenPayload = Buffer.concat([salt, iv, authTag, encrypted]);

    // 8. Encode the result as a URL-safe Base64 string for easy transport and storage.
    return tokenPayload.toString('base64url');
  } catch (error) {
    // Provide a more specific error message for better debugging.
    throw new Error(`Encryption failed: ${error.message}`);
  }
}

/**
 * Decrypts a token generated by the `encrypt` function.
 *
 * The process involves:
 * 1. Decoding the URL-safe Base64 token into a buffer.
 * 2. Parsing the buffer to extract the salt, IV, authentication tag, and ciphertext.
 * 3. Deriving the decryption key from the user secret and the extracted salt.
 * 4. Creating the AES-256-GCM decipher.
 * 5. Setting the authentication tag for integrity verification.
 * 6. Decrypting the ciphertext.
 *
 * @param {string} token - The URL-safe Base64 encoded token to decrypt.
 * @param {string} secret - The secret key string used for the original encryption.
 * @returns {Promise<string>} A promise that resolves to the original plaintext string.
 * @throws {Error} If the token is malformed, the secret is incorrect, or decryption fails (e.g., due to a tampered token).
 */
export async function decrypt(token, secret) {
  if (typeof token !== 'string' || token.length === 0) {
    throw new Error('Token to decrypt cannot be empty.');
  }
  if (typeof secret !== 'string' || secret.length === 0) {
    throw new Error('Decryption secret cannot be empty.');
  }

  try {
    // 1. Decode the URL-safe Base64 token.
    const tokenPayload = Buffer.from(token, 'base64url');

    // 2. Parse the components from the combined buffer.
    // The order and lengths must match the encryption process exactly.
    const salt = tokenPayload.subarray(0, 16);
    const iv = tokenPayload.subarray(16, 16 + IV_LENGTH);
    const authTag = tokenPayload.subarray(16 + IV_LENGTH, 16 + IV_LENGTH + AUTH_TAG_LENGTH);
    const encrypted = tokenPayload.subarray(16 + IV_LENGTH + AUTH_TAG_LENGTH);

    // Basic validation to prevent out-of-bounds errors.
    if (salt.length !== 16 || iv.length !== IV_LENGTH || authTag.length !== AUTH_TAG_LENGTH) {
      throw new Error('Invalid token format: component lengths are incorrect.');
    }

    // 3. Derive the key using the same salt and secret.
    const key = await deriveKey(secret, salt);

    // 4. Create the decipher.
    const decipher = createDecipheriv(ALGORITHM, key, iv);

    // 5. Set the authentication tag. This is crucial. If the tag doesn't match,
    // `decipher.final()` will throw an error, preventing decryption of tampered data.
    decipher.setAuthTag(authTag);

    // 6. Decrypt and return the plaintext.
    const decrypted = Buffer.concat([decipher.update(encrypted), decipher.final()]);

    return decrypted.toString(ENCODING);
  } catch (error) {
    // A common error is "Unsupported state or unable to authenticate data".
    // This typically means the secret is wrong or the token has been tampered with.
    // We return a generic but informative error to avoid leaking details.
    if (error.message.includes('Unsupported state')) {
      throw new Error('Decryption failed: Invalid secret or malformed/tampered token.');
    }
    throw new Error(`Decryption failed: ${error.message}`);
  }
}