/**
 * @file src/index.js
 * @description Main library entry point for the Basic Auth Obfuscator.
 *
 * This file serves as the public API for programmatic use of the obfuscator
 * in Node.js applications. It selectively exports the `decrypt` function from
 * the core logic, providing a simple and secure way to handle encrypted
 * credentials at runtime.
 *
 * The `encrypt` function is intentionally not exported here, as encryption is
 * primarily a one-time, offline task handled by the CLI. This design promotes
 * a secure workflow where encryption secrets are not needed in the runtime
 * environment of most applications.
 */

import { decrypt as coreDecrypt } from './core.js';

/**
 * Decrypts an opaque token back into its original plaintext string (e.g., "user:pass").
 *
 * This function is a wrapper around the core decryption logic, intended for
 * use in applications at runtime. It takes an encrypted token and the secret
* key (retrieved securely, e.g., from an environment variable) and returns
 * the original credentials.
 *
 * @function decrypt
 * @param {string} token - The URL-safe Base64 encoded token generated by the CLI's `encrypt` command.
 * @param {string} secret - The secret key string that was used for the original encryption.
 * @returns {Promise<string>} A promise that resolves to the original plaintext string.
 * @throws {Error} If the token is malformed, the secret is incorrect, or the token has been tampered with.
 *
 * @example
 * // In your application's startup code:
 * import { decrypt } from 'basic-auth-obfuscator';
 *
 * const encryptedToken = process.env.MY_APP_API_TOKEN;
 * const secretKey = process.env.MY_APP_DECRYPTION_KEY;
 *
 * try {
 *   const credentials = await decrypt(encryptedToken, secretKey);
 *   const [user, pass] = credentials.split(':');
 *   // Now use 'user' and 'pass' to make authenticated requests.
 * } catch (error) {
 *   console.error('Failed to decrypt credentials:', error);
 *   process.exit(1);
 * }
 */
export const decrypt = coreDecrypt;